-- WarungKita Supabase Schema
-- Jalankan di Supabase Dashboard > SQL Editor

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  stock integer not null default 0,
  unit text not null,
  min_stock_alert integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  total_amount numeric not null,
  status text not null,
  created_at text not null
);

-- Seed data
insert into public.products (name, category, price, stock, unit, min_stock_alert) values
  ('Beras Premium 5kg', 'Beras & Biji-bijian', 65000, 20, 'sak', 5),
  ('Minyak Goreng 1L', 'Minyak & Lemak', 18000, 15, 'botol', 5),
  ('Gula Pasir 1kg', 'Gula & Bumbu Dapur', 17000, 25, 'bungkus', 8),
  ('Telur Ayam 1kg', 'Sembako & Harian', 28000, 10, 'kg', 5),
  ('Kopi Kapal Api 1kg', 'Sembako & Harian', 45000, 12, 'bungkus', 4),
  ('Teh Pucuk Harum', 'Sembako & Harian', 3500, 40, 'botol', 10),
  ('Mie Instan Goreng', 'Sembako & Harian', 3500, 50, 'bungkus', 15),
  ('Kecap Manis Bango', 'Sembako & Harian', 32000, 8, 'botol', 3)
on conflict do nothing;

insert into public.transactions (customer_name, total_amount, status, created_at) values
  ('Budi Santoso', 98000, 'selesai', '2026-07-31T09:15:00.000Z'),
  ('Siti Aminah', 45000, 'selesai', '2026-07-31T10:30:00.000Z'),
  ('Ahmad Hidayat', 123500, 'selesai', '2026-07-31T13:45:00.000Z'),
  ('Dewi Lestari', 28000, 'proses', '2026-07-31T15:20:00.000Z'),
  ('Joko Widodo', 65000, 'selesai', '2026-08-01T08:05:00.000Z')
on conflict do nothing;

-- RLS: izinkan anon read/write (untuk demo sederhana)
alter table public.products enable row level security;
alter table public.transactions enable row level security;

create policy "products anon access" on public.products
  for all to anon using (true) with check (true);

create policy "transactions anon access" on public.transactions
  for all to anon using (true) with check (true);
